import React,{useMemo,useState}from"react";
import ReactDOM from"react-dom/client";
import{createClient}from"genlayer-js";
import{studionet}from"genlayer-js/chains";
import{TransactionStatus,type Hash}from"genlayer-js/types";
import"./styles.css";
import"./v3.css";

declare global{interface Window{ethereum?:{request:(x:{method:string})=>Promise<string[]>}}}
type Screening={screening_id:number;applicant:string;consumer:string;profile:{profile_ref:string;legal_name:string;aliases:string[];country:string;registration_id:string;birth_or_incorporation:string};official_source:string;state:string;relation:string;source_revision:string;source_digest:string;profile_digest:string;attempts:number;matched_fields:string[];conflicting_fields:string[]};
const EXPLORER="https://explorer-studio.genlayer.com";
const EMPTY_CONTRACT="0x3FAff7499A1eAC6100635267F594Ec6B0827Ee03";

function App(){
 const[account,setAccount]=useState(""),[contract,setContract]=useState(localStorage.getItem("entitymatch.contract")||EMPTY_CONTRACT),[id,setId]=useState("0"),[record,setRecord]=useState<Screening|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Paste the deployed contract address, then connect a StudioNet wallet.");
 const[consumer,setConsumer]=useState(""),[uid,setUid]=useState(""),[profileRef,setProfileRef]=useState("VENDOR-2026-001"),[name,setName]=useState("Northstar Industrial Trading Ltd"),[aliases,setAliases]=useState("Northstar Trading"),[country,setCountry]=useState("Singapore"),[registration,setRegistration]=useState("SG-201912345N"),[date,setDate]=useState("2019-04-18"),[journal,setJournal]=useState<{label:string;hash:string}[]>([]);
 const readClient=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 async function connect(){if(!window.ethereum)return setMessage("No injected wallet was found.");try{const a=await window.ethereum.request({method:"eth_requestAccounts"});if(!a[0])throw new Error("No account selected");const c=createClient({chain:studionet,provider:window.ethereum,account:a[0] as`0x${string}`});await c.connect("studionet");setAccount(a[0]);setMessage("Wallet connected. The deployer is not required for this workflow.")}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("entitymatch.contract",v);setRecord(null)}
 async function load(target=id){if(!valid)throw new Error("Set a valid deployed contract address");if(!/^\d+$/.test(String(target)))throw new Error("Screening ID must be a non-negative integer");const raw=await readClient.readContract({address:contract as`0x${string}`,functionName:"get_screening",args:[Number(target)]});if(raw==="NOT_FOUND")throw new Error("Screening not found");const parsed=JSON.parse(String(raw))as Screening;setRecord(parsed);return parsed}
 async function read(){setBusy("read");try{await load();setMessage("Authoritative contract state loaded.")}catch(e){setMessage(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 async function write(label:string,method:string,args:(string|number)[]){if(!valid||!account||!window.ethereum)return setMessage("Set the contract and connect a wallet first.");setBusy(method);try{const version=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_contract_version",args:[]})));if(version.name!=="EntityMatchGate"||version.version!==3)throw new Error("Contract schema mismatch. Write refused.");let target=id,before=-1;if(method==="open_screening"){before=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).screening_count;target=String(before)}const client=createClient({chain:studionet,provider:window.ethereum,account:account as`0x${string}`});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as`0x${string}`,functionName:method,args,value:0n}));setJournal(x=>[{label,hash},...x]);setMessage("Signed. Waiting for finality and authoritative readback...");await readClient.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(method==="open_screening"){const after=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).screening_count;if(after!==before+1)throw new Error("Finalized, but screening count did not advance");setId(target)}const post=await load(target);if(method==="dismiss_candidate"&&post.state!=="CANDIDATE_DISMISSED")throw new Error(`Dismissal was not confirmed; state is ${post.state}`);setMessage(`${label} finalized. Contract readback matched.`)}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const profile=JSON.stringify({schema:"entity-profile-v1",profile_ref:profileRef,legal_name:name,aliases:aliases.split("\n").map(x=>x.trim()).filter(Boolean),country,registration_id:registration,birth_or_incorporation:date});
 const openReady=valid&&!!account&&/^0x[0-9a-fA-F]{40}$/.test(consumer)&&consumer.toLowerCase()!==account.toLowerCase()&&!!uid&&!busy;
 return <div className="app"><header><a className="brand" href="#top"><img src="/entitymatch-logo.png"/><span><b>EntityMatchGate</b><small>Bounded identity screening</small></span></a><nav><a href="#how">How it works</a><a href="#operate">Operate</a><a href="#evidence">Evidence</a></nav><div className="network"><i/>StudioNet</div><button className="wallet" onClick={connect}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></header><main id="top">
 <section className="mast"><div className="mast-copy"><p className="eyebrow">CANDIDATE-SPECIFIC · BOUNDED CONSENSUS</p><h1>Review one match,<br/><em>without overclaiming.</em></h1><p>Compare one locked profile with one exact OFAC historical candidate. The result can close only that candidate review; it never clears or activates a vendor globally.</p><div className="principles"><span>01 Source bound</span><span>02 Profile locked</span><span>03 Exact candidate</span></div></div><div className="seal"><img src="/entitymatch-logo.png"/><p>Decision space</p><b>SAME</b><b>POSSIBLE</b><b>DISTINCT</b><b>INSUFFICIENT</b></div></section>
 <section className="how" id="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>One candidate. Two wallets. No deployer privilege.</h2></div><ol><li><span>01</span><div><b>Lock the profile</b><p>Wallet A records a canonical profile and names a different review consumer.</p></div></li><li><span>02</span><div><b>Assess exact candidate</b><p>Validators independently retrieve the selected OFAC entity record; contract binds its digest and revision.</p></div></li><li><span>03</span><div><b>Close only this candidate</b><p>Wallet B can dismiss this exact candidate only after DISTINCT_FROM_CANDIDATE and exact commitment recheck.</p></div></li></ol></section>
 <section className="contract"><label><span>Active contract</span><input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="0x… deploy with the primary wallet"/></label><label><span>Screening ID</span><input value={id} onChange={e=>setId(e.target.value)}/></label><button onClick={read} disabled={!valid||!!busy}>Load state</button></section>
 <section className="operate" id="operate"><article className="profile-card"><div className="card-title"><span>01</span><div><p className="eyebrow">APPLICANT WALLET</p><h2>Lock applicant profile</h2></div></div><div className="grid"><label>Profile reference<input value={profileRef} onChange={e=>setProfileRef(e.target.value)}/></label><label>Consumer wallet<input value={consumer} onChange={e=>setConsumer(e.target.value)} placeholder="Different wallet 0x…"/></label><label className="wide">Legal name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="wide">Aliases, one per line<textarea value={aliases} onChange={e=>setAliases(e.target.value)}/></label><label>Country<input value={country} onChange={e=>setCountry(e.target.value)}/></label><label>Registration ID<input value={registration} onChange={e=>setRegistration(e.target.value)}/></label><label>Birth / incorporation<input value={date} onChange={e=>setDate(e.target.value)}/></label><label>Official OFAC entry UID<input value={uid} onChange={e=>setUid(e.target.value)} placeholder="Exact uid from official snapshot"/></label></div><button className="primary" disabled={!openReady} onClick={()=>write("Open screening","open_screening",[consumer,profile,uid])}>{busy==="open_screening"?"Waiting for finality…":"Lock profile & open screening"}</button><p className="hint">Any wallet can create a screening. The deployer has no workflow role.</p></article>
 <aside className="decision-card"><div className="card-title"><span>02</span><div><p className="eyebrow">VALIDATORS + CONSUMER</p><h2>Assess & close candidate</h2></div></div><div className="decision"><small>Authoritative state</small><strong>{record?.state||"NOT LOADED"}</strong><p>{record?`${record.profile.legal_name} · UID ${record.official_source.split("/").pop()}`:"Load a review to see contract state."}</p></div><button className="primary violet" disabled={!valid||!account||!/^\d+$/.test(id)||!!busy||!!record&&record.attempts>=3} onClick={()=>write("Assess candidate","assess_screening",[Number(id)])}>{busy==="assess_screening"?"Validators are assessing…":"Run bounded assessment"}</button><button className="secondary" disabled={!valid||!account||record?.state!=="DISTINCT_FROM_CANDIDATE"||!!busy} onClick={()=>record&&write("Dismiss candidate","dismiss_candidate",[Number(id),record.profile_digest,record.source_digest,record.source_revision])}>{busy==="dismiss_candidate"?"Confirming dismissal…":"Dismiss exact candidate"}</button><p className="hint">Only the named consumer can dismiss this candidate. Same, possible or insufficient results remain open and grant no global clearance.</p></aside></section>
 <section className="readback" id="evidence"><div className="read-head"><div><p className="eyebrow">AUTHORITATIVE READBACK</p><h2>{record?.profile.profile_ref||"No review loaded"}</h2></div><span className={`status ${record?.state||""}`}>{record?.relation||"PENDING"}</span></div><div className="facts"><div><small>Candidate source</small><b>{record?<a href={record.official_source} target="_blank">OFAC entity {record.official_source.split("/").pop()}</a>:"—"}</b></div><div><small>Source revision</small><b>{record?.source_revision||"—"}</b></div><div><small>Source digest</small><b>{record?.source_digest||"—"}</b></div><div><small>Attempts</small><b>{record?.attempts??"—"} / 3</b></div><div><small>Matched fields</small><b>{record?.matched_fields.join(", ")||"—"}</b></div><div><small>Conflicting fields</small><b>{record?.conflicting_fields.join(", ")||"—"}</b></div></div><p className="source-note">This closes at most one historical candidate review. It is not active sanctions clearance, legal advice, or global vendor approval.</p></section>
 <section className="message"><b>Protocol status</b><p>{message}</p></section><section className="journal"><div><p className="eyebrow">TRANSACTION PROOF</p><h2>Finalized browser writes</h2></div>{journal.length?<div>{journal.map(x=><a key={x.hash} href={`${EXPLORER}/tx/${x.hash}`} target="_blank"><b>{x.label}</b><code>{x.hash.slice(0,14)}…{x.hash.slice(-8)}</code><span>Explorer</span></a>)}</div>:<p>No transaction has been signed in this browser session.</p>}</section></main><footer><img src="/entitymatch-logo.png"/><b>EntityMatchGate</b><p>Official-source identity screening with a deliberately narrow claim boundary.</p>{valid&&<a href={`${EXPLORER}/address/${contract}`} target="_blank">Contract on Explorer</a>}</footer></div>
}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
