import React,{useMemo,useState}from"react";
import ReactDOM from"react-dom/client";
import{createClient}from"genlayer-js";
import{studionet}from"genlayer-js/chains";
import{TransactionStatus,type Hash}from"genlayer-js/types";
import"./styles.css";import"./v3.css";

declare global{interface Window{ethereum?:{request:(x:{method:string})=>Promise<string[]>}}}
type Screening={screening_id:number;requester:string;relying_party:string;lei:string;official_entry_uid:string;state:string;relation:string;attempts:number;gleif_source:string;gleif_revision:string;gleif_digest:string;ofac_source:string;ofac_revision:string;ofac_digest:string;matched_fields:string[];conflicting_fields:string[];permit_consumer:string};
const EXPLORER="https://explorer-studio.genlayer.com";

function App(){
 const[account,setAccount]=useState(""),[contract,setContract]=useState(localStorage.getItem("entitymatch.v4.contract")||"0xeC8dc7def8232b4fa1d8a0fF64354eDE88E76e2f"),[id,setId]=useState("1"),[record,setRecord]=useState<Screening|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Connect a StudioNet wallet or load verified screening 1.");
 const[relyingParty,setRelyingParty]=useState(""),[uid,setUid]=useState("36"),[lei,setLei]=useState("5493001KJTIIGC8Y1R12"),[journal,setJournal]=useState<{label:string;hash:string}[]>([]);
 const readClient=useMemo(()=>createClient({chain:studionet}),[]),valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
 async function connect(){if(!window.ethereum)return setMessage("No injected wallet was found.");try{const a=await window.ethereum.request({method:"eth_requestAccounts"});if(!a[0])throw new Error("No account selected");const c=createClient({chain:studionet,provider:window.ethereum,account:a[0] as`0x${string}`});await c.connect("studionet");setAccount(a[0]);setMessage("Wallet connected. The deployer has no workflow privilege.")}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
 function saveContract(v:string){v=v.trim();setContract(v);localStorage.setItem("entitymatch.v4.contract",v);setRecord(null)}
 async function load(target=id){if(!valid)throw new Error("Set a valid v4 contract address");if(!/^\d+$/.test(String(target)))throw new Error("Screening ID must be non-negative");const raw=await readClient.readContract({address:contract as`0x${string}`,functionName:"get_screening",args:[Number(target)]});if(raw==="NOT_FOUND")throw new Error("Screening not found");const parsed=JSON.parse(String(raw))as Screening;setRecord(parsed);return parsed}
 async function read(){setBusy("read");try{await load();setMessage("Authoritative contract state loaded.")}catch(e){setMessage(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
 async function write(label:string,method:string,args:(string|number)[]){if(!valid||!account||!window.ethereum)return setMessage("Set the contract and connect a wallet first.");setBusy(method);try{const version=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_contract_version",args:[]})));if(version.name!=="EntityMatchGate"||version.version!==4)throw new Error("This is not EntityMatchGate v4. Write refused.");let target=id,before=-1;if(method==="open_screening"){before=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).screening_count;target=String(before)}const client=createClient({chain:studionet,provider:window.ethereum,account:account as`0x${string}`});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as`0x${string}`,functionName:method,args,value:0n}));setJournal(x=>[{label,hash},...x]);setMessage("Signed. Waiting for finality and authoritative readback...");await readClient.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(method==="open_screening"){const after=JSON.parse(String(await readClient.readContract({address:contract as`0x${string}`,functionName:"get_counts",args:[]}))).screening_count;if(after!==before+1)throw new Error("Finalized, but count did not advance");setId(target)}const post=await load(target);const expected:Record<string,string>={activate_permit:"PERMIT_ACTIVE",consume_permit:"PERMIT_CONSUMED"};if(expected[method]&&post.state!==expected[method])throw new Error(`State mismatch: expected ${expected[method]}, got ${post.state}`);setMessage(`${label} finalized. Contract readback matched.`)}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
 const openReady=valid&&!!account&&/^0x[0-9a-fA-F]{40}$/.test(relyingParty)&&relyingParty.toLowerCase()!==account.toLowerCase()&&/^[A-Z0-9]{20}$/.test(lei)&&!!uid&&!busy;
 return <div className="app"><header><a className="brand" href="#top"><img src="/entitymatch-logo.png"/><span><b>EntityMatchGate</b><small>Official-source permit</small></span></a><nav><a href="#how">How it works</a><a href="#operate">Operate</a><a href="#evidence">Evidence</a></nav><div className="network"><i/>StudioNet</div><button className="wallet" onClick={connect}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></header><main id="top">
 <section className="mast"><div className="mast-copy"><p className="eyebrow">OFFICIAL-TO-OFFICIAL · ONE-TIME AUTHORIZATION</p><h1>Resolve one candidate,<br/><em>then consume the permit.</em></h1><p>Validators compare an official GLEIF legal-entity record with one exact OFAC historical candidate. Only a strong distinct result can create a one-time on-chain permit.</p><div className="principles"><span>01 GLEIF bound</span><span>02 OFAC bound</span><span>03 Permit consumed</span></div></div><div className="seal"><img src="/entitymatch-logo.png"/><p>Decision space</p><b>SAME</b><b>POSSIBLE</b><b>DISTINCT</b><b>INSUFFICIENT</b></div></section>
 <section className="how" id="how"><div><p className="eyebrow">HOW IT WORKS</p><h2>Two official sources. Two wallets. No deployer privilege.</h2></div><ol><li><span>01</span><div><b>Lock source IDs</b><p>Wallet A locks one LEI, one OFAC UID and a different relying-party wallet.</p></div></li><li><span>02</span><div><b>Validators fetch both</b><p>Validators retrieve GLEIF and OFAC, bind both digests, and re-execute the semantic comparison.</p></div></li><li><span>03</span><div><b>Activate and consume</b><p>Only DISTINCT permits activation; only Wallet B can consume the permit, exactly once.</p></div></li></ol></section>
 <section className="contract"><label><span>Active v4 contract</span><input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="0x… deploy with the primary wallet"/></label><label><span>Screening ID</span><input value={id} onChange={e=>setId(e.target.value)}/></label><button onClick={read} disabled={!valid||!!busy}>Load state</button></section>
 <section className="operate" id="operate"><article className="profile-card"><div className="card-title"><span>01</span><div><p className="eyebrow">REQUESTER WALLET</p><h2>Lock official source IDs</h2></div></div><div className="grid"><label>GLEIF LEI<input value={lei} onChange={e=>setLei(e.target.value.toUpperCase())} maxLength={20}/></label><label>Relying-party wallet<input value={relyingParty} onChange={e=>setRelyingParty(e.target.value)} placeholder="Different wallet 0x…"/></label><label>Official OFAC entry UID<input value={uid} onChange={e=>setUid(e.target.value)} placeholder="Exact entity UID"/></label></div><button className="primary" disabled={!openReady} onClick={()=>write("Open screening","open_screening",[relyingParty,lei,uid])}>{busy==="open_screening"?"Waiting for finality…":"Lock sources & open screening"}</button><p className="hint">No legal name or registration fact is self-asserted. Validators retrieve those facts from GLEIF.</p></article>
 <aside className="decision-card"><div className="card-title"><span>02</span><div><p className="eyebrow">VALIDATORS + TWO ROLES</p><h2>Assess, activate & consume</h2></div></div><div className="decision"><small>Authoritative state</small><strong>{record?.state||"NOT LOADED"}</strong><p>{record?`LEI ${record.lei} · OFAC UID ${record.official_entry_uid}`:"Load a review to see contract state."}</p></div><button className="primary violet" disabled={!valid||!account||!/^[0-9]+$/.test(id)||!!busy||!!record&&record.attempts>=3} onClick={()=>write("Assess candidate","assess_screening",[Number(id)])}>{busy==="assess_screening"?"Validators are assessing…":"Run official-source assessment"}</button><button className="secondary" disabled={!valid||!account||record?.state!=="DISTINCT_FROM_CANDIDATE"||!!busy} onClick={()=>record&&write("Activate permit","activate_permit",[Number(id),record.gleif_digest,record.ofac_digest])}>{busy==="activate_permit"?"Activating…":"Activate one-time permit"}</button><button className="secondary" disabled={!valid||!account||record?.state!=="PERMIT_ACTIVE"||!!busy} onClick={()=>write("Consume permit","consume_permit",[Number(id)])}>{busy==="consume_permit"?"Consuming…":"Consume permit"}</button><p className="hint">Same, possible or insufficient results cannot activate. Activation is requester-only; consumption is relying-party-only.</p></aside></section>
 <section className="readback" id="evidence"><div className="read-head"><div><p className="eyebrow">AUTHORITATIVE READBACK</p><h2>{record?.lei||"No review loaded"}</h2></div><span className={`status ${record?.state||""}`}>{record?.state||"PENDING"}</span></div><div className="facts"><div><small>Independent entity source</small><b>{record?<a href={record.gleif_source} target="_blank">GLEIF {record.lei}</a>:"—"}</b></div><div><small>Candidate source</small><b>{record?<a href={record.ofac_source} target="_blank">OFAC entity {record.official_entry_uid}</a>:"—"}</b></div><div><small>GLEIF revision / digest</small><b>{record?`${record.gleif_revision} · ${record.gleif_digest}`:"—"}</b></div><div><small>OFAC revision / digest</small><b>{record?`${record.ofac_revision} · ${record.ofac_digest}`:"—"}</b></div><div><small>Attempts</small><b>{record?.attempts??"—"} / 3</b></div><div><small>Matched / conflicting</small><b>{record?`${record.matched_fields.join(", ")||"—"} / ${record.conflicting_fields.join(", ")||"—"}`:"—"}</b></div><div><small>Permit consumer</small><b>{record?.permit_consumer||"Not consumed"}</b></div></div><p className="source-note">This authorizes one relying party for one exact GLEIF-vs-OFAC candidate decision. It is not current sanctions clearance or legal advice.</p></section>
 <section className="message"><b>Protocol status</b><p>{message}</p></section><section className="journal"><div><p className="eyebrow">TRANSACTION PROOF</p><h2>Finalized browser writes</h2></div>{journal.length?<div>{journal.map(x=><a key={x.hash} href={`${EXPLORER}/tx/${x.hash}`} target="_blank"><b>{x.label}</b><code>{x.hash.slice(0,14)}…{x.hash.slice(-8)}</code><span>Explorer</span></a>)}</div>:<p>No transaction has been signed in this browser session.</p>}</section></main><footer><img src="/entitymatch-logo.png"/><b>EntityMatchGate</b><p>Official-to-official identity resolution with a consumable on-chain consequence.</p>{valid&&<a href={`${EXPLORER}/address/${contract}`} target="_blank">Contract on Explorer</a>}</footer></div>
}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
